path:
  dataset: cifar100
  postfix: test

setup:
  model_type: deep
  batch_size: 128
  cpus: 4
  gpus: "2"
  seed: 0
  num_epoch: 2
  phase: train
  adv_training: True

module:
  model:
    name: densebc
    num_classes: 100
    dropout_rate: 0.0

  optim:
    name: SGD
    lr: 0.1
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0005

  lr_scheduler:
    name: CosineAnnealingLR
    T_max: 200

  # loss: [CrossEntropyLoss]
    # CrossEntropyLoss:
  loss: [BrierLoss]
  loss_args:
    BrierLoss:
      num_classes: 100
      reduction: mean
  loss_weight: [1.]
  val_metric: Accuracy
  test_metric: Accuracy
  metric_args:
    nlabels: 100
    reduction: none