path:
  dataset: cifar100
  postfix: none

setup:
  model_type: mcd
  batch_size: 128
  cpus: 32
  gpus: "0"
  seed: 0
  num_epoch: 200
  phase: train
  num_mc: 5
  adv_training: False

module:
  model:
    name: densebc
    num_classes: 100
    dropout_rate: 0.2

  optim:
    name: SGD
    lr: 0.1
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0005

  lr_scheduler:
    name: CosineAnnealingLR
    T_max: 200

  loss: [CrossEntropyLoss]
  loss_args:
    CrossEntropyLoss:
      reduction: mean
  loss_weight: [1.]
  val_metric: Accuracy
  test_metric: Accuracy
  metric_args:
    nlabels: 100
    reduction: none