path:
  dataset: voc
  postfix: none

setup:
  model_type: seg
  batch_size: 30
  cpus: 4
  gpus: "4,5"
  seed: 0
  num_epoch: 200
  phase: train
  epoch_th: 0
  num_mc: 100
  n_a: 256
  adv_training: False

module:
  model:
    name: deeplabv3_res101
    num_classes: 21
    # dropout_rate: 0.0

  optim:
    name: SGD
    lr: 0.001
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0005

  lr_scheduler:
    name: CosineAnnealingLR
    T_max: 200

  loss: [CrossEntropyLoss]
  loss_args:
    CrossEntropyLoss:
      reduction: mean
  loss_weight: [1.]
  val_metric: MeanIOU 
  test_metric: MeanIOU
  metric_args:
    nlabels: 21
    reduction: none